package rules;

import be.kuleuven.pylos.Move
import be.kuleuven.pylos.game.PylosBoard
import be.kuleuven.pylos.game.PylosGame
import be.kuleuven.pylos.game.PylosLocation
import be.kuleuven.pylos.game.PylosSphere
import be.kuleuven.pylos.game.PylosSquare
import be.kuleuven.pylos.player.student.PylosLine
import java.util.Arrays

global be.kuleuven.pylos.player.student.StudentPlayerRuleEngine player

rule "Remove own 4"
salience 0
when
    board : PylosBoard()
    PylosGame( state == state.REMOVE_FIRST )
    square : PylosSquare( getInSquare() == 4 && (getInSquare( player ) == 4 ) )
then
    //get remaining location in square
    PylosLocation location = Arrays.stream( square.getLocations())
        .filter( l -> !l.hasAbove() )
        .findFirst()
        .get();

    player.addMove( new Move( location, location.getSphere() ), 1 );
end